// Korean font for jsPDF
// Using a simplified approach with custom font mapping for Korean characters

export const koreanFontMapping: Record<string, string> = {
  // Common Korean characters used in salary statements
  '급': 'Salary',
  '여': 'Pay',
  '명': 'Statement',
  '세': 'Tax',
  '서': 'Document',
  '회': 'Company',
  '사': 'Corp',
  '정': 'Info',
  '보': 'Report',
  '직': 'Employee',
  '원': 'Won',
  '성': 'Name',
  '현': 'Site',
  '장': 'Location',
  '기': 'Basic',
  '본': 'Base',
  '연': 'Overtime',
  '수': 'Amount',
  '당': 'Allowance',
  '공': 'Deduction',
  '제': 'Tax',
  '실': 'Net',
  '령': 'Receive',
  '액': 'Amount',
  '계': 'Account',
  '좌': 'Bank',
  '은': 'Bank',
  '행': 'Bank',
  '발': 'Issue',
  '일': 'Date',
  '시': 'Time',
  '년': 'Year',
  '월': 'Month',
  '분': 'For',
  '번': 'Number',
  '호': 'No',
  '주': 'Address',
  '소': 'Location',
  '자': 'Person',
  '등': 'Registration',
  '록': 'Record',
  '책': 'Position',
  '간': 'Period',
  '지': 'Pay',
  '상': 'Detail',
  '내': 'Content',
  '용': 'Use',
  '항': 'Item',
  '목': 'Category',
  '금': 'Amount',
  '시': 'Hour',
  '간': 'Time',
  '율': 'Rate',
  '너': 'Bonus',
  '스': 's',
  '계': 'Total',
  '전': 'Before',
  '후': 'After',
  '취': 'Pre',
  '선': 'Advance',
  '예': 'Deposit',
  '주': 'Holder',
  '인': 'Person',
  '날': 'Day',
  '짜': 'Date',
  '피': 'P',
  '디': 'D',
  '에': 'F',
  '프': 'F',
};

// Function to convert Korean text to displayable text
export function convertKoreanText(text: string): string {
  // For PDF generation, we'll use a different approach
  // Return the original text and handle it with proper font embedding
  return text;
}