import { RequestData, ProductionData, ShippingData } from './types'

export const REQUEST_DATA: RequestData[] = [
  {
    id: 'r1',
    type: 'request',
    site: '강남 A현장',
    date: '2025. 11. 11',
    material: 'NPC-1000',
    qty: 25,
    priority: 'urgent',
    memo: 'TEST 자재요청 (긴급처리 요망)',
  },
  {
    id: 'r2',
    type: 'request',
    site: '서초 B현장',
    date: '2025. 11. 21',
    material: 'NPC-3000Q',
    qty: 30,
    priority: 'low',
    partner: '대한건설(주)',
  },
  {
    id: 'r3',
    type: 'request',
    site: '송파 C현장',
    date: '2025. 10. 16',
    material: 'NPC-1000',
    qty: 103,
    priority: 'high',
    memo: 'Seeded for 2025-10',
  },
  {
    id: 'r4',
    type: 'request',
    site: '인천공항 T3 확장',
    date: '2025. 10. 22',
    material: 'NPC-1000',
    qty: 51,
    priority: 'normal',
  },
  {
    id: 'r5',
    type: 'request',
    site: '방배 D현장',
    date: '2025. 10. 31',
    material: 'NPC-3000Q',
    qty: 51,
    priority: 'high',
    memo: '현장 진입로 협소',
  },
  {
    id: 'r6',
    type: 'request',
    site: '수원 영통구 A지구',
    date: '2025. 10. 14',
    material: 'NPC-3000Q',
    qty: 54,
    priority: 'urgent',
  },
  {
    id: 'r7',
    type: 'request',
    site: '강남 A현장',
    date: '2025. 11. 11',
    material: 'NPC-1000',
    qty: 50,
    priority: 'normal',
    memo: '[일반] 추가 요청',
  },
]

export const PRODUCTION_DATA: ProductionData[] = [
  {
    id: 'p1',
    type: 'production',
    date: '2025. 11. 24',
    site: '자이 아파트 101동',
    partner: '서울전기공사',
    productionQty: 50,
    material: 'NPC-1000 외 1건',
    additionalMaterial: 'NPC-3000Q (20개)',
  },
  {
    id: 'p2',
    type: 'production',
    date: '2025. 11. 24',
    site: '삼성 반도체 P3',
    partner: '서울전기공사',
    productionQty: 20,
    material: 'NPC-1000',
  },
  {
    id: 'p3',
    type: 'production',
    date: '2025. 11. 21',
    site: '자이 아파트 103동',
    partner: '서울전기공사',
    productionQty: 50,
    material: 'NPC-3000Q',
  },
  {
    id: 'p4',
    type: 'production',
    date: '2025. 11. 13',
    site: '삼성 반도체 P4',
    partner: '서울전기공사',
    productionQty: 345,
    material: 'NPC-3000Q',
  },
  {
    id: 'p5',
    type: 'production',
    date: '2025. 11. 13',
    site: '자이 아파트 105동',
    partner: '서울전기공사',
    productionQty: 500,
    material: 'NPC-3000Q',
    additionalMaterial: '메모 테스트',
  },
  {
    id: 'p6',
    type: 'production',
    date: '2025. 11. 13',
    site: '삼성 반도체 P3',
    partner: '서울전기공사',
    productionQty: 225,
    material: 'NPC-1000',
  },
]

export const SHIPPING_DATA: ShippingData[] = [
  {
    id: 's1',
    type: 'shipping',
    date: '2025. 11. 20',
    site: '강남 A현장',
    partner: '서울전기공사',
    status: 'done',
    material: 'NPC-1000 외 1건',
    totalQty: 60,
    amount: 2280000,
    tags: ['월말청구', '화물', '착불'],
  },
  {
    id: 's2',
    type: 'shipping',
    date: '2025. 11. 13',
    site: '삼성전자 P3',
    partner: '대한건설(주)',
    status: 'waiting',
    material: 'NPC-3000Q',
    totalQty: 234,
    amount: 8500000,
    tags: ['용차', '선불'],
  },
  {
    id: 's3',
    type: 'shipping',
    date: '2025. 11. 10',
    site: '서초 B현장',
    partner: '한국배관시스템',
    status: 'done',
    material: 'NPC-1000',
    totalQty: 100,
    amount: 3500000,
    tags: ['월말청구'],
  },
  {
    id: 's4',
    type: 'shipping',
    date: '2025. 11. 05',
    site: '송파 C현장',
    partner: '서울전기공사',
    status: 'done',
    material: 'NPC-2000',
    totalQty: 45,
    amount: 1200000,
    tags: ['택배'],
  },
  {
    id: 's5',
    type: 'shipping',
    date: '2025. 10. 30',
    site: '인천공항 T3',
    partner: '대한건설(주)',
    status: 'waiting',
    material: 'NPC-3000Q',
    totalQty: 120,
    amount: 4800000,
    tags: ['용차'],
  },
  {
    id: 's6',
    type: 'shipping',
    date: '2025. 10. 25',
    site: '강남 A현장',
    partner: '서울전기공사',
    status: 'done',
    material: 'NPC-1000',
    totalQty: 10,
    amount: 380000,
    tags: ['화물'],
  },
]
